---
 - name: Play - Another Register Example
   hosts: planetexpress
   gather_facts: true
   connection: ssh

   tasks:
     - name: Reach out with geturl to random generation
       get_url:
         url: https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new
         dest: ~/rand.txt
         force: yes
         
     - name: Read the rand.txt and save results in randvarz
       command: cat ~/rand.txt
       register: randvarz
       
     - name: "Debug - display a win"
       debug:
         msg: "Congratulations! {{ ansible_hostname }} won :)"
       when: randvarz.stdout == "1"

     - name: "Debug - display a failure"
       debug:
         msg: "Sorry. {{ ansible_hostname }} lost :("
       when: randvarz.stdout == "0"

